// <auto-generated />
using System;
using LifeTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408082644_AddPurchases")]
    partial class AddPurchases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LifeTracker.Models.EconomyBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DailyResetAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyTaskCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GoldMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInPenaltyPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDailyCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("MultiplierExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PenaltyEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PenaltyMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalGoldEarned")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalGoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalXpEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("XpMultiplier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique();

                    b.ToTable("EconomyBalances");
                });

            modelBuilder.Entity("LifeTracker.Models.GameTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChecklistJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("OverdueProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemindersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepeatPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("GameTasks");
                });

            modelBuilder.Entity("LifeTracker.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentXp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeathCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DeathTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RecoveryEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalXpEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("LifeTracker.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("LifeTracker.Models.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");
                });

            modelBuilder.Entity("LifeTracker.Models.Streak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FreezeActiveUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("FreezeCharges")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShieldActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastBreakDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<int>("LongestDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ShieldExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalBreaks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("Streaks");
                });

            modelBuilder.Entity("LifeTracker.Models.EconomyBalance", b =>
                {
                    b.HasOne("LifeTracker.Models.Hero", "Hero")
                        .WithOne("EconomyBalance")
                        .HasForeignKey("LifeTracker.Models.EconomyBalance", "HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("LifeTracker.Models.GameTask", b =>
                {
                    b.HasOne("LifeTracker.Models.Hero", "Hero")
                        .WithMany("Tasks")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("LifeTracker.Models.Purchase", b =>
                {
                    b.HasOne("LifeTracker.Models.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeTracker.Models.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("LifeTracker.Models.Streak", b =>
                {
                    b.HasOne("LifeTracker.Models.Hero", "Hero")
                        .WithMany("Streaks")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeTracker.Models.GameTask", "Task")
                        .WithOne("Streak")
                        .HasForeignKey("LifeTracker.Models.Streak", "TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hero");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("LifeTracker.Models.GameTask", b =>
                {
                    b.Navigation("Streak");
                });

            modelBuilder.Entity("LifeTracker.Models.Hero", b =>
                {
                    b.Navigation("EconomyBalance");

                    b.Navigation("Streaks");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
