// <auto-generated />
using System;
using LifeTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeTracker.Models.DailyTaskCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ConsumedLastXpBoostCharge")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsumedXpBoostCharge")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PreviousStreakCurrentDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PreviousStreakLastCheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousStreakLastCheckInLocalDate")
                        .HasColumnType("text");

                    b.Property<int?>("PreviousStreakLongestDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PreviousStreakStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreviousTaskCompletionCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PreviousTaskLastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreviousXpBoostPercent")
                        .HasColumnType("integer");

                    b.Property<int>("RewardGold")
                        .HasColumnType("integer");

                    b.Property<long>("RewardXp")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("StreakExistedBefore")
                        .HasColumnType("boolean");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("HeroId", "TaskId", "LocalDate")
                        .IsUnique();

                    b.ToTable("DailyTaskCompletions");
                });

            modelBuilder.Entity("LifeTracker.Models.EconomyBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DailyResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyTaskCompletions")
                        .HasColumnType("integer");

                    b.Property<decimal>("GoldMultiplier")
                        .HasColumnType("numeric");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInPenaltyPeriod")
                        .HasColumnType("boolean");

                    b.Property<string>("LastDailyResetLocalDate")
                        .HasColumnType("text");

                    b.Property<int>("MaxDailyCompletions")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("MultiplierExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PenaltyEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PenaltyMultiplier")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("TotalGoldEarned")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalGoldSpent")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalXpEarned")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("XpMultiplier")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique();

                    b.ToTable("EconomyBalances");
                });

            modelBuilder.Entity("LifeTracker.Models.GameTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecklistJson")
                        .HasColumnType("text");

                    b.Property<int>("CompletionCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailCount")
                        .HasColumnType("integer");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMissedScheduledLocalDate")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("OverdueProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Polarity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("RemindersJson")
                        .HasColumnType("text");

                    b.Property<string>("RepeatPattern")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("GameTasks");
                });

            modelBuilder.Entity("LifeTracker.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentXp")
                        .HasColumnType("bigint");

                    b.Property<int>("DeathCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeathTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShieldActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastTimeZoneChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerDeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PendingTimeZoneId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RecoveryEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ShieldActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UTC");

                    b.Property<string>("TimeZoneSwitchAfterLocalDate")
                        .HasColumnType("text");

                    b.Property<long>("TotalXpEarned")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("XpBoostPercent")
                        .HasColumnType("integer");

                    b.Property<int>("XpBoostTasksRemaining")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerDeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("LifeTracker.Models.HeroAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GoldReward")
                        .HasColumnType("integer");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Key")
                        .IsUnique();

                    b.ToTable("HeroAchievements");
                });

            modelBuilder.Entity("LifeTracker.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GoldSpent")
                        .HasColumnType("integer");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("LifeTracker.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LifeTracker.Models.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EffectValue")
                        .HasColumnType("integer");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");
                });

            modelBuilder.Entity("LifeTracker.Models.Streak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FreezeActiveUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FreezeCharges")
                        .HasColumnType("integer");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsShieldActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastBreakDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastBreakLocalDate")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastCheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastCheckInLocalDate")
                        .HasColumnType("text");

                    b.Property<int>("LongestDays")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ShieldBackupBreakAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ShieldBackupCurrentDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ShieldExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ShieldFailConsumed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBreaks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("Streaks");
                });

            modelBuilder.Entity("LifeTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LifeTracker.Models.DailyTaskCompletion", b =>
                {
                    b.HasOne("LifeTracker.Models.Hero", "Hero")
                        .WithMany("DailyTaskCompletions")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeTracker.Models.GameTask", "Task")
                        .WithMany("DailyTaskCompletions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("LifeTracker.Models.EconomyBalance", b =>
                {
                    b.HasOne("LifeTracker.Models.Hero", "Hero")
                        .WithOne("EconomyBalance")
                        .HasForeignKey("LifeTracker.Models.EconomyBalance", "HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("LifeTracker.Models.GameTask", b =>
                {
                    b.HasOne("LifeTracker.Models.Hero", "Hero")
                        .WithMany("Tasks")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("LifeTracker.Models.Hero", b =>
                {
                    b.HasOne("LifeTracker.Models.User", "User")
                        .WithMany("Heroes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeTracker.Models.Purchase", b =>
                {
                    b.HasOne("LifeTracker.Models.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeTracker.Models.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("LifeTracker.Models.RefreshToken", b =>
                {
                    b.HasOne("LifeTracker.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeTracker.Models.Streak", b =>
                {
                    b.HasOne("LifeTracker.Models.Hero", "Hero")
                        .WithMany("Streaks")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeTracker.Models.GameTask", "Task")
                        .WithOne("Streak")
                        .HasForeignKey("LifeTracker.Models.Streak", "TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hero");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("LifeTracker.Models.GameTask", b =>
                {
                    b.Navigation("DailyTaskCompletions");

                    b.Navigation("Streak");
                });

            modelBuilder.Entity("LifeTracker.Models.Hero", b =>
                {
                    b.Navigation("DailyTaskCompletions");

                    b.Navigation("EconomyBalance");

                    b.Navigation("Streaks");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("LifeTracker.Models.User", b =>
                {
                    b.Navigation("Heroes");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
